//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T150112_TranPhuHoa_PhoneShopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangSX
    {
        public HangSX()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaHSX { get; set; }
        public string TenHSX { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
