//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T150112_TranPhuHoa_PhoneShopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturer
    {
        public manufacturer()
        {
            this.products = new HashSet<product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
